config/routes.rb
Rails.application.routes.draw do
  get "checkout/:session_id" => "checkout_sessions#show", as: :checkout
  get "checkout" => "checkout_sessions#new", as: :new_checkout
  post "checkout" => "checkout_sessions#create"

  resources :certificates
  get "certificates/:id/preview" => "certificates#preview", as: :preview_certificate

  get "documents/index" => "documents#index"

  # Rails built-in authentication
  resource :session
  resources :passwords, param: :token

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "certificates#index"
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :user

  store_accessor(:data,
    :graduate_name,
    :degree,
    :major,
    :nouns,
    :honoree_name,
    :message,
    :presented_on,
    :signature_path
  )
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  include Printable

  before_action :set_certificate, only: %i[ show edit update destroy preview ]
  before_action :options_for_nouns, only: %i[ index edit new create show ]

  # GET /certificates or /certificates.json
  def index
    @certificates = Certificate.where(user: Current.user)
  end

  # GET /certificates/1 or /certificates/1.json
  def show
  end

  # GET /certificates/new
  def new
    existing_certificate = Certificate.where(
      user: Current.user
    ).last

    attrs = existing_certificate ? existing_certificate.data.except("honoree_name") : {}

    @certificate = Certificate.new(attrs)
  end

  # GET /certificates/1/edit
  def edit
  end

  # POST /certificates or /certificates.json
  def create
    @certificate = Certificate.new(certificate_params[:certificate])

    respond_to do |format|
      if @certificate.save
        format.html { redirect_to @certificate, notice: "★ Certificate was created" }
        format.json { render :show, status: :created, location: @certificate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificates/1 or /certificates/1.json
  def update
    respond_to do |format|
      if @certificate.update(certificate_params[:certificate])
        format.html do
          if @certificate.saved_changes?
            redirect_to certificates_path, notice: "Certificate for #{@certificate.honoree_name} was updated"
          else
            redirect_to certificates_path
          end
        end
        format.json { render :show, status: :ok, location: @certificate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificates/1 or /certificates/1.json
  def destroy
    @certificate.destroy!

    respond_to do |format|
      format.html { redirect_to certificates_path, notice: "✖︎ Certificate was deleted", status: :see_other }
      format.json { head :no_content }
    end
  end

  def preview
    respond_to do |format|
      format.pdf
      format.png
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate
      @certificate = Certificate.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def certificate_params
      params.permit(
        :id,
        certificate: [
          :graduate_name,
          :degree,
          :major,
          :honoree_name,
          :presented_on,
          :signature_path,
          :message,
          :user_id,
          nouns: []
        ]
      )
    end

    def options_for_nouns
      @options_for_nouns ||= %w[Love Support Guidance Mentorship Patience]
    end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_action_buttons.html.erb
<div data-controller="visibility">
  <%= render "form_modal", certificate: certificate %>

  <div class="flex flex-col md:flex-row justify-center gap-8" data-visibility-target="hideable">
    <%= form_with(url: new_checkout_path, data: { turbo: false }, method: :get) do |f| %>
      <input type="hidden" id="price_id" name="price_id" value="price_1S7JZoBKCB1NBOVa2U4OXmFy" />
      <%= f.submit "Checkout", class: "w-full min-w-48 text-background dark:text-background-dark sm:w-auto text-center rounded-md px-3 py-2 bg-primary/80 hover:bg-primary dark:bg-primary-dark/80 dark:hover:bg-primary-dark inline-block font-medium" %>
    <% end %>

    <% if show_edit %>
      <button command="show-modal" commandfor="certificate-form" class="w-full min-w-48 text-background dark:text-background-dark sm:w-auto text-center rounded-md px-3 py-2 bg-primary/80 hover:bg-primary dark:bg-primary-dark/80 dark:hover:bg-primary-dark inline-block font-medium">Edit</button>
    <% end %>

    <%= button_to "✖︎ Delete", certificate, method: :delete, class: "w-full min-w-48 text-background dark:text-background-dark sm:w-auto text-center rounded-md px-3 py-2 bg-error/80 hover:bg-error inline-block font-medium", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>

app/views/certificates/_certificate.html.erb
  <div style="background-image: url('<%= asset_path("blank_westtown.png") %>'); background-size: cover; background-position: center; background-repeat: no-repeat;" class="
    rounded-xl
    h-[418.671875] w-[542]
    md:h-[395.5] md:w-[512]
    lg:h-[527.3125] lg:w-[682.65625]
    xl:h-[659.140625] xl:w-[853.328125]
    2xl:h-[791] 2xl:w-[1024]
    mx-auto
    shadow-xl dark:shadow-none
    mb-4
  ">
    <img
      alt="Your certificate"
      class="rounded-xl"
      data-controller="preview"
      data-preview-target="img"
      data-preview-src-value="<%= "#{preview_certificate_path(certificate.id)}.png" %>"
    />
  </div>

app/views/certificates/_form.html.erb
<%= form_with(model: certificate, class: "contents flex flex-col gap-6", data: { turbo: false }) do |form| %>
  <% if certificate.errors.any? %>
    <div id="error_explanation" class="bg-error/20 text-error px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul class="list-disc ml-6">
        <% certificate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col lg:flex-row gap-4">
    <div class="flex flex-col w-full">
      <%= form.label :graduate_name, class: form_label_classes %>
      <%= form.text_field :graduate_name, class: form_input_classes(certificate), type: :search %>
    </div>

    <div class="flex flex-col w-full">
      <%= form.label :honoree_name, class: form_label_classes %>
      <%= form.text_field :honoree_name, class: form_input_classes(certificate), type: :search %>
    </div>
  </div>

  <div class="flex flex-col lg:flex-row gap-4">
    <div class="flex flex-col w-full">
      <%= form.label :major, class: form_label_classes %>
      <%= form.text_field :major, class: form_input_classes(certificate), type: :search %>
    </div>

    <div class="flex flex-col w-full">
      <%= form.label :degree, class: form_label_classes %>
      <%= form.text_field :degree, class: form_input_classes(certificate), type: :search %>
    </div>

    <div class="flex flex-col w-full">
      <%= form.label "Graduation date", class: form_label_classes %>
      <%= form.text_field :presented_on, class: form_input_classes(certificate), type: :search %>
    </div>
  </div>

  <div class="flex flex-col lg:flex-row gap-4">
    <div class="flex flex-col w-full">
      <%= form.label "Why", class: form_label_classes %>
      <%= form.select :nouns, options_for_select(@options_for_nouns, certificate.nouns), { include_blank: false }, {multiple: true, class: "h-30 #{form_input_classes(certificate)}"} %>
    </div>

    <div class="flex flex-col w-full">
      <%= form.label :message, class: form_label_classes %>
      <%= form.text_area :message, class: "h-30 #{form_input_classes(certificate)}" %>
    </div>
  </div>

  <%= form.hidden_field :signature_path, value: "givers_signature.png" %>
  <%= form.hidden_field :user_id, value: Current.user.id %>

  <div class="flex flex-col md:flex-row justify-center gap-8 my-8 text-background dark:text-background-dark">
    <%= form.submit "Save", class: "w-full min-w-48 sm:w-auto text-center rounded-md px-3 py-2 bg-primary/80 hover:bg-primary dark:bg-primary-dark/80 dark:hover:bg-primary-dark inline-block font-medium cursor-pointer" %>

    <button command="close" commandfor="certificate-form" type="button" class="w-full min-w-48 text-background dark:text-background-dark sm:w-auto text-center rounded-md px-3 py-2 bg-error/80 hover:bg-error inline-block font-medium">Close</button>
  </div>
<% end %>

app/views/certificates/_form_modal.html.erb
<!--
e.g.: UI element to invoke this modal:
<button command="show-modal" commandfor="certificate-form" type="button">
  Show modal
</button>
-->

<el-dialog>
  <dialog id="certificate-form" class="backdrop:bg-black/50 transition duration-200 data-closed:opacity-0" command="close" commandfor="certificate-form" >
    <el-dialog-panel class="fixed transition duration-200 data-closed:scale-70 data-closed:opacity-0">
      <div class="min-h-screen min-w-screen flex justify-center items-center">
        <div class="p-8 bg-background/90  dark:bg-background-dark/90 rounded-xl shadow-lg">
          <h2 class="mb-10 flex justify-between items-center">
            <span class="font-bold text-3xl">Edit certificate</span>
            
            <button command="close" commandfor="certificate-form" type="button" class="text-2xl hover:cursor-pointer text-content-muted/70 hover:text-content-muted dark:text-content-muted-dark/70 dark:hover:text-content-muted-dark">✖︎</button>
          </h2>

          <%= render "form", certificate: certificate %>
        </div>
      </div>
    </el-dialog-panel>
  </dialog>
</el-dialog>

app/views/certificates/_notice.html.erb
<div class="p-8 bg-success/20 font-medium rounded-md inline-block" id="notice">
  <div class="flex justify-between items-baseline">
    <div class="text-2xl font-semibold">
      <span class="text-success"> ★ </span>
      <%= notice || "Certificate #{certificate && "for {#certificate.honoree_name}"} was updated" %> 
    </div>
  </div>
</div>

app/views/certificates/edit.html.erb
<% content_for :title do %>
  Edit Certificate
<% end %>

<div class="mt-8 mx-auto md:w-2/3 w-full flex flex-col gap-8">
  <h1 class="font-bold text-4xl">
    Certificate for <%= @certificate.honoree_name %>
  </h1>

  <%= render "form", certificate: @certificate %>
</div>

app/views/certificates/index.html.erb
<% content_for :title, "My Certificates" %>

<div class="mx-auto md:w-2/3 w-full flex flex-col gap-8">
  <div class="flex justify-center items-center">
    <%# <h1 class="font-headline text-3xl">My Certificates</h1> %>

    <%== link_to "✚ New", new_certificate_path, class: "w-full min-w-48 text-background dark:text-background-dark sm:w-auto text-center rounded-md px-3 py-2 bg-primary/80 dark:bg-primary-dark/80 hover:bg-primary dark:hov inline-block font-medium" %>
  </div>

  <% if notice.present? %>
    <%= render partial: "notice", locals: {certificate: @certificate} %>
  <% end %>

  <div id="certificates" class="min-w-full flex flex-col gap-16">
    <% if @certificates.any? %>
      <% @certificates.each do |certificate| %>
        <div class="flex flex-col gap-8">
          <%= render certificate %>

          <%= render partial: "action_buttons", locals: {certificate: certificate, show_edit: true} %>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No certificates found.</p>
    <% end %>
  </div>
</div>

app/views/certificates/new.html.erb
<% content_for :title do %>
  Create a Certificate
<% end %>

<div class="mx-auto md:w-2/3 w-full flex flex-col gap-8">
  <h1 class="font-bold text-4xl">New Certificate</h1>

  <%= render "form", certificate: @certificate %>
</div>

app/views/certificates/show.html.erb
<% content_for :title do %>
  Preview
<% end %>

<div class="mx-auto md:w-2/3 w-full flex flex-col gap-8">
  <div class="flex justify-between items-center gap-4">
    <h1 class="font-bold text-4xl">Preview</h1>

    <%= link_to "My certificates", certificates_path, class: "w-36 text-white sm:w-auto text-center rounded-md px-3 py-2 bg-primary/70 hover:bg-primary inline-block font-medium" %>
  </div>

  <% if notice.present? %>
    <%= render partial: "notice", locals: {certificate: @certificate} %>

  <% end %>

  <%= render @certificate %>

  <%= render partial: "action_buttons", locals: {certificate: @certificate, show_edit: true} %>

</div>